language: python
sudo: false
python:
    - 3.5
    - 3.5-dev
install:
    - pip install .
before_script:
    - pylint --rcfile .pylintrc mymcadmin
script:
    - nosetests --with-coverage --cover-package=mymcadmin --cover-min-percentage=95 --rednose

